(function (root) {
  'use strict';
  const keys = 'canvas|workspace|newSession|connecting|connected|retry|gestures|emptyTitle|emptyBody|connectSession|session|createTitle|createBody|name|runtime|close|cancel|createSession|creating|relationship|linkTitle|linkTo|linkBody|addConnection|available|unavailable|unknownAvailability|unknownRuntime|notInstalled|added|createdFrom|linked|sessions|sessionActions|needAnother|bridgeUnavailable|invalidState|created|positionError|pythonHelp|cliHelp|workspaceChanged'.split('|');
  const rows = {
    en: 'Session canvas|Workspace|New session|Connecting…|Native sessions|Retry|Drag to move · Scroll to pan · Pinch to zoom|A place for your sessions|Open a real terminal and follow where the work goes.|Connect|Session|Start something new|Create a standalone terminal in this workspace.|Name|Run|Close|Cancel|Create session|Creating…|Relationship|Connect two sessions|Connect to|Adds a relationship without sharing conversation history or changing either session.|Add connection|Terminal available|Terminal unavailable|Availability unknown|Unknown runtime|Not installed|Added {date}|Created from|Linked|Sessions|Session actions|Create another session to add a connection.|Open this canvas inside the OMG cmux app.|The native app returned invalid canvas data. Retry to reconnect.|Session created|Position could not be saved.|Opens an interactive Python prompt.|Opens the CLI without sending a prompt.|The workspace changed. Reopen this canvas.',
    de: 'Sitzungsübersicht|Arbeitsbereich|Neue Sitzung|Verbindung wird hergestellt…|Native Sitzungen|Erneut versuchen|Ziehen zum Bewegen · Scrollen zum Verschieben · Aufziehen zum Zoomen|Ein Platz für deine Sitzungen|Öffne ein echtes Terminal und verfolge den Verlauf der Arbeit.|Verbinden|Sitzung|Etwas Neues beginnen|Ein unabhängiges Terminal in diesem Arbeitsbereich erstellen.|Name|Ausführen|Schließen|Abbrechen|Sitzung erstellen|Wird erstellt…|Beziehung|Zwei Sitzungen verbinden|Verknüpfen mit|Fügt eine Beziehung hinzu, ohne den Gesprächsverlauf zu teilen oder eine Sitzung zu ändern.|Verbindung hinzufügen|Terminal verfügbar|Terminal nicht verfügbar|Verfügbarkeit unbekannt|Unbekannte Laufzeit|Nicht installiert|Hinzugefügt: {date}|Erstellt aus|Verknüpft|Sitzungen|Sitzungsaktionen|Erstelle eine weitere Sitzung, um eine Verbindung hinzuzufügen.|Öffne diese Übersicht in der OMG-cmux-App.|Die native App hat ungültige Daten zurückgegeben. Versuche die Verbindung erneut.|Sitzung erstellt|Die Position konnte nicht gespeichert werden.|Öffnet eine interaktive Python-Eingabe.|Öffnet die CLI, ohne eine Eingabe zu senden.|Der Arbeitsbereich wurde geändert. Öffne diese Übersicht erneut.',
    fr: 'Canevas des sessions|Espace de travail|Nouvelle session|Connexion…|Sessions natives|Réessayer|Glisser pour déplacer · Défiler pour naviguer · Pincer pour zoomer|Un espace pour vos sessions|Ouvrez un vrai terminal et suivez le parcours du travail.|Connecter|Session|Commencer quelque chose|Créer un terminal indépendant dans cet espace de travail.|Nom|Exécuter|Fermer|Annuler|Créer la session|Création…|Relation|Relier deux sessions|Lier à|Ajoute une relation sans partager l’historique ni modifier les sessions.|Ajouter la liaison|Terminal disponible|Terminal indisponible|Disponibilité inconnue|Environnement inconnu|Non installé|Ajouté le {date}|Créé depuis|Lié|Sessions|Actions de session|Créez une autre session pour ajouter une liaison.|Ouvrez ce canevas dans l’application OMG cmux.|L’application native a renvoyé des données invalides. Réessayez la connexion.|Session créée|Impossible d’enregistrer la position.|Ouvre une invite Python interactive.|Ouvre la CLI sans envoyer de message.|L’espace de travail a changé. Rouvrez ce canevas.',
    ar: 'لوحة الجلسات|مساحة العمل|جلسة جديدة|جارٍ الاتصال…|جلسات أصلية|إعادة المحاولة|اسحب للتحريك · مرر للتنقل · باعد إصبعيك للتكبير|مساحة لجلساتك|افتح طرفية حقيقية وتابع مسار العمل.|ربط|جلسة|ابدأ شيئًا جديدًا|أنشئ طرفية مستقلة في مساحة العمل هذه.|الاسم|تشغيل|إغلاق|إلغاء|إنشاء جلسة|جارٍ الإنشاء…|علاقة|ربط جلستين|ربط بـ|يضيف علاقة دون مشاركة سجل المحادثة أو تغيير أي جلسة.|إضافة رابط|الطرفية متاحة|الطرفية غير متاحة|التوفر غير معروف|بيئة تشغيل غير معروفة|غير مثبت|أضيفت في {date}|أُنشئت من|مرتبطة|الجلسات|إجراءات الجلسة|أنشئ جلسة أخرى لإضافة رابط.|افتح هذه اللوحة داخل تطبيق OMG cmux.|أعاد التطبيق بيانات لوحة غير صالحة. أعد محاولة الاتصال.|تم إنشاء الجلسة|تعذر حفظ الموضع.|يفتح موجه Python تفاعليًا.|يفتح واجهة سطر الأوامر دون إرسال رسالة.|تغيرت مساحة العمل. أعد فتح هذه اللوحة.',
    es: 'Lienzo de sesiones|Espacio de trabajo|Nueva sesión|Conectando…|Sesiones nativas|Reintentar|Arrastrar para mover · Desplazar para navegar · Pellizcar para ampliar|Un espacio para tus sesiones|Abre un terminal real y sigue el recorrido del trabajo.|Conectar|Sesión|Empieza algo nuevo|Crea un terminal independiente en este espacio de trabajo.|Nombre|Ejecutar|Cerrar|Cancelar|Crear sesión|Creando…|Relación|Conectar dos sesiones|Vincular a|Añade una relación sin compartir el historial ni modificar ninguna sesión.|Añadir conexión|Terminal disponible|Terminal no disponible|Disponibilidad desconocida|Entorno desconocido|No instalado|Añadido el {date}|Creado desde|Vinculado|Sesiones|Acciones de sesión|Crea otra sesión para añadir una conexión.|Abre este lienzo en la aplicación OMG cmux.|La aplicación nativa devolvió datos no válidos. Reintenta la conexión.|Sesión creada|No se pudo guardar la posición.|Abre un intérprete interactivo de Python.|Abre la CLI sin enviar ningún mensaje.|El espacio de trabajo cambió. Vuelve a abrir este lienzo.',
    'zh-Hant': '工作階段畫布|工作區|新增工作階段|連線中…|原生工作階段|重試|拖曳以移動 · 捲動以平移 · 捏合以縮放|為工作階段留一個位置|開啟真正的終端機，追蹤工作的來龍去脈。|連接|工作階段|開始新的工作|在此工作區建立獨立的終端機。|名稱|執行|關閉|取消|建立工作階段|建立中…|關係|連結兩個工作階段|連結至|新增關係，不會共用對話記錄或變更任何工作階段。|新增連結|終端機可用|終端機不可用|可用狀態未知|未知執行環境|未安裝|加入於 {date}|建立來源|已連結|工作階段|工作階段操作|請先建立另一個工作階段，再新增連結。|請在 OMG cmux 應用程式中開啟此畫布。|原生應用程式傳回無效的畫布資料。請重試連線。|已建立工作階段|無法儲存位置。|開啟互動式 Python 提示字元。|開啟 CLI，不會傳送提示詞。|工作區已變更。請重新開啟此畫布。',
    'zh-Hans': '会话画布|工作区|新建会话|正在连接…|原生会话|重试|拖动以移动 · 滚动以平移 · 双指捏合以缩放|为会话留一个位置|打开真正的终端，追踪工作的来龙去脉。|连接|会话|开始新的工作|在此工作区创建独立的终端。|名称|运行|关闭|取消|创建会话|正在创建…|关系|连接两个会话|关联到|添加关系，不会共享对话历史或更改任何会话。|添加连接|终端可用|终端不可用|可用状态未知|未知运行环境|未安装|添加于 {date}|创建来源|已关联|会话|会话操作|请先创建另一个会话，再添加连接。|请在 OMG cmux 应用中打开此画布。|原生应用返回了无效的画布数据。请重试连接。|会话已创建|无法保存位置。|打开交互式 Python 提示符。|打开 CLI，不发送提示词。|工作区已更改。请重新打开此画布。',
    ko: '세션 캔버스|작업 공간|새 세션|연결 중…|네이티브 세션|다시 시도|드래그하여 이동 · 스크롤하여 탐색 · 핀치하여 확대/축소|세션을 위한 공간|실제 터미널을 열고 작업의 흐름을 따라가세요.|연결|세션|새 작업 시작|이 작업 공간에 독립된 터미널을 만듭니다.|이름|실행|닫기|취소|세션 만들기|만드는 중…|관계|두 세션 연결|연결 대상|대화 기록을 공유하거나 세션을 변경하지 않고 관계를 추가합니다.|연결 추가|터미널 사용 가능|터미널 사용 불가|사용 가능 여부 알 수 없음|알 수 없는 실행 환경|설치되지 않음|추가됨: {date}|생성 출처|연결됨|세션|세션 작업|연결을 추가하려면 다른 세션을 만드세요.|OMG cmux 앱에서 이 캔버스를 여세요.|네이티브 앱에서 잘못된 캔버스 데이터를 반환했습니다. 다시 연결하세요.|세션이 생성되었습니다|위치를 저장할 수 없습니다.|대화형 Python 프롬프트를 엽니다.|메시지를 보내지 않고 CLI를 엽니다.|작업 공간이 변경되었습니다. 캔버스를 다시 여세요.',
    ja: 'セッションキャンバス|ワークスペース|新しいセッション|接続中…|ネイティブセッション|再試行|ドラッグで移動 · スクロールでパン · ピンチでズーム|セッションのための場所|本物のターミナルを開き、作業の流れをたどります。|接続|セッション|新しい作業を始める|このワークスペースに独立したターミナルを作成します。|名前|実行|閉じる|キャンセル|セッションを作成|作成中…|関係|2つのセッションをつなぐ|関連付け先|会話履歴を共有したり、セッションを変更したりせずに関係を追加します。|接続を追加|ターミナルは利用可能|ターミナルは利用不可|利用可否は不明|実行環境は不明|未インストール|追加日: {date}|作成元|関連付け|セッション|セッション操作|接続を追加するには、別のセッションを作成してください。|OMG cmux アプリでこのキャンバスを開いてください。|ネイティブアプリから無効なデータが返されました。接続を再試行してください。|セッションを作成しました|位置を保存できませんでした。|対話型の Python プロンプトを開きます。|プロンプトを送信せずに CLI を開きます。|ワークスペースが変更されました。このキャンバスを開き直してください。'
  };
  const catalogs = Object.fromEntries(Object.entries(rows).map(([locale, row]) => {
    const values = row.split('|');
    if (values.length !== keys.length) throw new Error(`Invalid OMG message catalog: ${locale}`);
    return [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))];
  }));
  const historyKeys = ["searchSessions", "includeWorkers", "shownCount", "noMatches", "history", "summary", "noSummary", "source", "originalSession", "originalCreated", "updated", "recordedStatus", "statusUnknown", "runtimeConfig", "workingDirectory", "evidence", "noEvidence", "lineage", "noLineage", "resume", "resuming", "openTerminal", "resumeUnavailable", "roleConductor", "roleMission", "roleWorker", "roleReference", "roleUnknown", "spawn", "fork", "handoff", "continuation", "recordedOn", "searchResults", "resultCount", "from", "to", "historicalHint", "unknownDate", "filteredLineage"];
  const historyRows = {
  "en": "Search sessions|Show all sessions|{shown} / {total} sessions|No matching sessions|Session history|Summary|No summary was recorded.|Source|Original session|Created|Last activity|Recorded status|Not recorded|Runtime configuration|Working directory|Source evidence|No source references were recorded.|Lineage|No relationship was recorded for this session.|Resume session|Resuming…|Open terminal|A matching local CLI session is not available to resume.|Conductor|Mission|Worker|Reference|Role unknown|Spawned|Forked|Handoff|Continued|{date}|Search results|{shown} / {total} results|From|To|This is a historical record. Resume opens the original local CLI session.|Date unknown|{count} relationships hidden by filters",
  "de": "Sitzungen suchen|Alle Sitzungen|{shown} / {total} Sitzungen|Keine passenden Sitzungen|Sitzungsverlauf|Zusammenfassung|Keine Zusammenfassung erfasst.|Quelle|Ursprüngliche Sitzung|Erstellt|Letzte Aktivität|Erfasster Status|Nicht erfasst|Laufzeitkonfiguration|Arbeitsverzeichnis|Quellnachweise|Keine Quellverweise erfasst.|Abstammung|Für diese Sitzung wurde keine Beziehung erfasst.|Sitzung fortsetzen|Wird fortgesetzt…|Terminal öffnen|Keine passende lokale CLI-Sitzung zum Fortsetzen verfügbar.|Leitsitzung|Mission|Worker|Referenz|Rolle unbekannt|Gestartet|Abgezweigt|Übergabe|Fortgesetzt|{date}|Suchergebnisse|{shown} / {total} Ergebnisse|Von|An|Dies ist ein historischer Eintrag. Fortsetzen öffnet die ursprüngliche lokale CLI-Sitzung.|Datum unbekannt|{count} Beziehungen durch Filter ausgeblendet",
  "fr": "Rechercher des sessions|Toutes les sessions|{shown} / {total} sessions|Aucune session correspondante|Historique de session|Résumé|Aucun résumé enregistré.|Source|Session d’origine|Création|Dernière activité|État enregistré|Non enregistré|Configuration d’exécution|Dossier de travail|Preuves des sources|Aucune référence source enregistrée.|Filiation|Aucune relation enregistrée pour cette session.|Reprendre la session|Reprise…|Ouvrir le terminal|Aucune session CLI locale correspondante ne peut être reprise.|Conducteur|Mission|Agent|Référence|Rôle inconnu|Création déléguée|Branche|Transfert|Continuation|{date}|Résultats de recherche|{shown} / {total} résultats|De|Vers|Il s’agit d’un historique. Reprendre ouvre la session CLI locale d’origine.|Date inconnue|{count} relations masquées par les filtres",
  "ar": "البحث في الجلسات|عرض كل الجلسات|{shown} / {total} جلسة|لا توجد جلسات مطابقة|سجل الجلسة|الملخص|لم يتم تسجيل ملخص.|المصدر|الجلسة الأصلية|تاريخ الإنشاء|آخر نشاط|الحالة المسجلة|غير مسجل|إعدادات التشغيل|مجلد العمل|أدلة المصدر|لم يتم تسجيل مراجع للمصدر.|النسب|لم يتم تسجيل علاقة لهذه الجلسة.|استئناف الجلسة|جارٍ الاستئناف…|فتح الطرفية|لا تتوفر جلسة محلية مطابقة في واجهة سطر الأوامر لاستئنافها.|المنسق|المهمة|العامل|المرجع|الدور غير معروف|إنشاء فرعي|تفرع|تسليم|متابعة|{date}|نتائج البحث|{shown} / {total} نتيجة|من|إلى|هذا سجل تاريخي. يفتح الاستئناف جلسة سطر الأوامر المحلية الأصلية.|التاريخ غير معروف|تم إخفاء {count} علاقة بواسطة المرشحات",
  "es": "Buscar sesiones|Todas las sesiones|{shown} / {total} sesiones|No hay sesiones coincidentes|Historial de sesión|Resumen|No se registró ningún resumen.|Origen|Sesión original|Creación|Última actividad|Estado registrado|No registrado|Configuración de ejecución|Directorio de trabajo|Evidencias del origen|No se registraron referencias de origen.|Linaje|No se registró ninguna relación para esta sesión.|Reanudar sesión|Reanudando…|Abrir terminal|No hay una sesión CLI local coincidente que se pueda reanudar.|Conductor|Misión|Agente|Referencia|Rol desconocido|Delegación|Bifurcación|Traspaso|Continuación|{date}|Resultados de búsqueda|{shown} / {total} resultados|De|A|Este es un registro histórico. Reanudar abre la sesión CLI local original.|Fecha desconocida|{count} relaciones ocultas por los filtros",
  "zh-Hant": "搜尋工作階段|所有工作階段|{shown} / {total} 個工作階段|沒有符合的工作階段|工作階段歷史|摘要|未記錄摘要。|來源|原始工作階段|建立時間|最後活動|記錄的狀態|未記錄|執行環境設定|工作目錄|來源依據|未記錄來源參考。|沿革|此工作階段未記錄關係。|繼續工作階段|正在繼續…|開啟終端機|沒有可繼續的相符本機 CLI 工作階段。|主控|任務|子代理|參考|角色未知|派生|分支|交接|延續|{date}|搜尋結果|{shown} / {total} 個結果|來自|前往|這是歷史記錄。繼續將開啟原始本機 CLI 工作階段。|日期未知|篩選器隱藏了 {count} 個關係",
  "zh-Hans": "搜索会话|所有会话|{shown} / {total} 个会话|没有匹配的会话|会话历史|摘要|未记录摘要。|来源|原始会话|创建时间|最后活动|记录的状态|未记录|运行环境配置|工作目录|来源依据|未记录来源参考。|沿革|此会话未记录关系。|继续会话|正在继续…|打开终端|没有可继续的匹配本地 CLI 会话。|主控|任务|子代理|参考|角色未知|派生|分支|交接|延续|{date}|搜索结果|{shown} / {total} 个结果|来自|前往|这是历史记录。继续将打开原始本地 CLI 会话。|日期未知|筛选器隐藏了 {count} 个关系",
  "ko": "세션 검색|모든 세션 표시|{shown} / {total}개 세션|일치하는 세션 없음|세션 기록|요약|기록된 요약이 없습니다.|출처|원본 세션|생성일|마지막 활동|기록된 상태|기록 없음|런타임 구성|작업 디렉터리|출처 근거|기록된 출처 참조가 없습니다.|계보|이 세션에 기록된 관계가 없습니다.|세션 재개|재개 중…|터미널 열기|재개할 수 있는 일치하는 로컬 CLI 세션이 없습니다.|지휘자|미션|작업자|참조|역할 알 수 없음|생성|분기|인계|계속|{date}|검색 결과|{shown} / {total}개 결과|출발|도착|과거 기록입니다. 재개하면 원래 로컬 CLI 세션이 열립니다.|날짜 알 수 없음|필터로 숨겨진 관계: {count}개",
  "ja": "セッションを検索|すべてのセッション|{shown} / {total} セッション|一致するセッションはありません|セッション履歴|概要|概要は記録されていません。|出典|元のセッション|作成日時|最終アクティビティ|記録された状態|記録なし|実行環境の設定|作業ディレクトリ|出典の根拠|出典の参照は記録されていません。|系譜|このセッションの関係は記録されていません。|セッションを再開|再開中…|ターミナルを開く|再開できる一致したローカル CLI セッションがありません。|指揮者|ミッション|ワーカー|参照|役割は不明|生成|分岐|引き継ぎ|継続|{date}|検索結果|{shown} / {total} 件|元|先|これは履歴です。再開すると元のローカル CLI セッションが開きます。|日付は不明|フィルターで非表示の関係: {count} 件"
};
  for (const [locale, row] of Object.entries(historyRows)) {
    const values = row.split('|');
    if (values.length !== historyKeys.length) throw new Error(`Invalid OMG history catalog: ${locale}`);
    Object.assign(catalogs[locale], Object.fromEntries(historyKeys.map((key, i) => [key, values[i]])));
  }
  keys.push(...historyKeys);
  const observationLabels = {"en": "Observation", "de": "Beobachtung", "fr": "Observation", "ar": "رصد", "es": "Observación", "zh-Hant": "觀測記錄", "zh-Hans": "观测记录", "ko": "관찰 기록", "ja": "観測記録"};
  for (const [locale,label] of Object.entries(observationLabels)) catalogs[locale].roleObservation=label;
  keys.push('roleObservation');
  const chatPreviewLabels = {"en": "Chat preview", "de": "Chat-Vorschau", "fr": "Aperçu du chat", "ar": "معاينة المحادثة", "es": "Vista previa del chat", "zh-Hant": "聊天預覽", "zh-Hans": "聊天预览", "ko": "채팅 미리보기", "ja": "チャットプレビュー"};
  for (const [locale, label] of Object.entries(chatPreviewLabels)) catalogs[locale].chatPreview = label;
  keys.push('chatPreview');
  function localeFor(value) {
    const language = String(value || 'en').replaceAll('_', '-');
    if (/^zh-(TW|HK|MO|Hant)/i.test(language)) return 'zh-Hant';
    if (/^zh/i.test(language)) return 'zh-Hans';
    return catalogs[language] ? language : catalogs[language.split('-')[0]] ? language.split('-')[0] : 'en';
  }
  function translate(locale, key, values = {}) {
    const message = catalogs[localeFor(locale)][key] || catalogs.en[key] || key;
    return message.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
  }
  const api = {catalogs, keys, localeFor, translate};
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.OMGCanvasMessages = api;
})(typeof globalThis === 'object' ? globalThis : this);
