(function (root) {
  'use strict';
  const keys = 'canvas|workspace|newSession|connecting|connected|retry|gestures|emptyTitle|emptyBody|connectSession|session|createTitle|createBody|name|runtime|close|cancel|createSession|creating|relationship|linkTitle|linkTo|linkBody|addConnection|available|unavailable|unknownAvailability|unknownRuntime|notInstalled|added|createdFrom|linked|sessions|sessionActions|needAnother|bridgeUnavailable|invalidState|created|positionError|pythonHelp|cliHelp|workspaceChanged'.split('|');
  const rows = {
    en: 'Session canvas|Workspace|New session|Connecting…|Native sessions|Retry|Drag to move · Scroll to pan · Pinch to zoom|A place for your sessions|Open a real terminal and follow where the work goes.|Connect|Session|Start something new|Create a standalone terminal in this workspace.|Name|Run|Close|Cancel|Create session|Creating…|Relationship|Connect two sessions|Connect to|Adds a relationship without sharing conversation history or changing either session.|Add connection|Terminal available|Terminal unavailable|Availability unknown|Unknown runtime|Not installed|Added {date}|Created from|Linked|Sessions|Session actions|Create another session to add a connection.|Open this canvas inside the OMG cmux app.|The native app returned invalid canvas data. Retry to reconnect.|Session created|Position could not be saved.|Opens an interactive Python prompt.|Opens the CLI without sending a prompt.|The workspace changed. Reopen this canvas.',
    de: 'Sitzungsübersicht|Arbeitsbereich|Neue Sitzung|Verbindung wird hergestellt…|Native Sitzungen|Erneut versuchen|Ziehen zum Bewegen · Scrollen zum Verschieben · Aufziehen zum Zoomen|Ein Platz für deine Sitzungen|Öffne ein echtes Terminal und verfolge den Verlauf der Arbeit.|Verbinden|Sitzung|Etwas Neues beginnen|Ein unabhängiges Terminal in diesem Arbeitsbereich erstellen.|Name|Ausführen|Schließen|Abbrechen|Sitzung erstellen|Wird erstellt…|Beziehung|Zwei Sitzungen verbinden|Verknüpfen mit|Fügt eine Beziehung hinzu, ohne den Gesprächsverlauf zu teilen oder eine Sitzung zu ändern.|Verbindung hinzufügen|Terminal verfügbar|Terminal nicht verfügbar|Verfügbarkeit unbekannt|Unbekannte Laufzeit|Nicht installiert|Hinzugefügt: {date}|Erstellt aus|Verknüpft|Sitzungen|Sitzungsaktionen|Erstelle eine weitere Sitzung, um eine Verbindung hinzuzufügen.|Öffne diese Übersicht in der OMG-cmux-App.|Die native App hat ungültige Daten zurückgegeben. Versuche die Verbindung erneut.|Sitzung erstellt|Die Position konnte nicht gespeichert werden.|Öffnet eine interaktive Python-Eingabe.|Öffnet die CLI, ohne eine Eingabe zu senden.|Der Arbeitsbereich wurde geändert. Öffne diese Übersicht erneut.',
    fr: 'Canevas des sessions|Espace de travail|Nouvelle session|Connexion…|Sessions natives|Réessayer|Glisser pour déplacer · Défiler pour naviguer · Pincer pour zoomer|Un espace pour vos sessions|Ouvrez un vrai terminal et suivez le parcours du travail.|Connecter|Session|Commencer quelque chose|Créer un terminal indépendant dans cet espace de travail.|Nom|Exécuter|Fermer|Annuler|Créer la session|Création…|Relation|Relier deux sessions|Lier à|Ajoute une relation sans partager l’historique ni modifier les sessions.|Ajouter la liaison|Terminal disponible|Terminal indisponible|Disponibilité inconnue|Environnement inconnu|Non installé|Ajouté le {date}|Créé depuis|Lié|Sessions|Actions de session|Créez une autre session pour ajouter une liaison.|Ouvrez ce canevas dans l’application OMG cmux.|L’application native a renvoyé des données invalides. Réessayez la connexion.|Session créée|Impossible d’enregistrer la position.|Ouvre une invite Python interactive.|Ouvre la CLI sans envoyer de message.|L’espace de travail a changé. Rouvrez ce canevas.',
    ar: 'لوحة الجلسات|مساحة العمل|جلسة جديدة|جارٍ الاتصال…|جلسات أصلية|إعادة المحاولة|اسحب للتحريك · مرر للتنقل · باعد إصبعيك للتكبير|مساحة لجلساتك|افتح طرفية حقيقية وتابع مسار العمل.|ربط|جلسة|ابدأ شيئًا جديدًا|أنشئ طرفية مستقلة في مساحة العمل هذه.|الاسم|تشغيل|إغلاق|إلغاء|إنشاء جلسة|جارٍ الإنشاء…|علاقة|ربط جلستين|ربط بـ|يضيف علاقة دون مشاركة سجل المحادثة أو تغيير أي جلسة.|إضافة رابط|الطرفية متاحة|الطرفية غير متاحة|التوفر غير معروف|بيئة تشغيل غير معروفة|غير مثبت|أضيفت في {date}|أُنشئت من|مرتبطة|الجلسات|إجراءات الجلسة|أنشئ جلسة أخرى لإضافة رابط.|افتح هذه اللوحة داخل تطبيق OMG cmux.|أعاد التطبيق بيانات لوحة غير صالحة. أعد محاولة الاتصال.|تم إنشاء الجلسة|تعذر حفظ الموضع.|يفتح موجه Python تفاعليًا.|يفتح واجهة سطر الأوامر دون إرسال رسالة.|تغيرت مساحة العمل. أعد فتح هذه اللوحة.',
    es: 'Lienzo de sesiones|Espacio de trabajo|Nueva sesión|Conectando…|Sesiones nativas|Reintentar|Arrastrar para mover · Desplazar para navegar · Pellizcar para ampliar|Un espacio para tus sesiones|Abre un terminal real y sigue el recorrido del trabajo.|Conectar|Sesión|Empieza algo nuevo|Crea un terminal independiente en este espacio de trabajo.|Nombre|Ejecutar|Cerrar|Cancelar|Crear sesión|Creando…|Relación|Conectar dos sesiones|Vincular a|Añade una relación sin compartir el historial ni modificar ninguna sesión.|Añadir conexión|Terminal disponible|Terminal no disponible|Disponibilidad desconocida|Entorno desconocido|No instalado|Añadido el {date}|Creado desde|Vinculado|Sesiones|Acciones de sesión|Crea otra sesión para añadir una conexión.|Abre este lienzo en la aplicación OMG cmux.|La aplicación nativa devolvió datos no válidos. Reintenta la conexión.|Sesión creada|No se pudo guardar la posición.|Abre un intérprete interactivo de Python.|Abre la CLI sin enviar ningún mensaje.|El espacio de trabajo cambió. Vuelve a abrir este lienzo.',
    'zh-Hant': '工作階段畫布|工作區|新增工作階段|連線中…|原生工作階段|重試|拖曳以移動 · 捲動以平移 · 捏合以縮放|為工作階段留一個位置|開啟真正的終端機，追蹤工作的來龍去脈。|連接|工作階段|開始新的工作|在此工作區建立獨立的終端機。|名稱|執行|關閉|取消|建立工作階段|建立中…|關係|連結兩個工作階段|連結至|新增關係，不會共用對話記錄或變更任何工作階段。|新增連結|終端機可用|終端機不可用|可用狀態未知|未知執行環境|未安裝|加入於 {date}|建立來源|已連結|工作階段|工作階段操作|請先建立另一個工作階段，再新增連結。|請在 OMG cmux 應用程式中開啟此畫布。|原生應用程式傳回無效的畫布資料。請重試連線。|已建立工作階段|無法儲存位置。|開啟互動式 Python 提示字元。|開啟 CLI，不會傳送提示詞。|工作區已變更。請重新開啟此畫布。',
    'zh-Hans': '会话画布|工作区|新建会话|正在连接…|原生会话|重试|拖动以移动 · 滚动以平移 · 双指捏合以缩放|为会话留一个位置|打开真正的终端，追踪工作的来龙去脉。|连接|会话|开始新的工作|在此工作区创建独立的终端。|名称|运行|关闭|取消|创建会话|正在创建…|关系|连接两个会话|关联到|添加关系，不会共享对话历史或更改任何会话。|添加连接|终端可用|终端不可用|可用状态未知|未知运行环境|未安装|添加于 {date}|创建来源|已关联|会话|会话操作|请先创建另一个会话，再添加连接。|请在 OMG cmux 应用中打开此画布。|原生应用返回了无效的画布数据。请重试连接。|会话已创建|无法保存位置。|打开交互式 Python 提示符。|打开 CLI，不发送提示词。|工作区已更改。请重新打开此画布。',
    ko: '세션 캔버스|작업 공간|새 세션|연결 중…|네이티브 세션|다시 시도|드래그하여 이동 · 스크롤하여 탐색 · 핀치하여 확대/축소|세션을 위한 공간|실제 터미널을 열고 작업의 흐름을 따라가세요.|연결|세션|새 작업 시작|이 작업 공간에 독립된 터미널을 만듭니다.|이름|실행|닫기|취소|세션 만들기|만드는 중…|관계|두 세션 연결|연결 대상|대화 기록을 공유하거나 세션을 변경하지 않고 관계를 추가합니다.|연결 추가|터미널 사용 가능|터미널 사용 불가|사용 가능 여부 알 수 없음|알 수 없는 실행 환경|설치되지 않음|추가됨: {date}|생성 출처|연결됨|세션|세션 작업|연결을 추가하려면 다른 세션을 만드세요.|OMG cmux 앱에서 이 캔버스를 여세요.|네이티브 앱에서 잘못된 캔버스 데이터를 반환했습니다. 다시 연결하세요.|세션이 생성되었습니다|위치를 저장할 수 없습니다.|대화형 Python 프롬프트를 엽니다.|메시지를 보내지 않고 CLI를 엽니다.|작업 공간이 변경되었습니다. 캔버스를 다시 여세요.',
    ja: 'セッションキャンバス|ワークスペース|新しいセッション|接続中…|ネイティブセッション|再試行|ドラッグで移動 · スクロールでパン · ピンチでズーム|セッションのための場所|本物のターミナルを開き、作業の流れをたどります。|接続|セッション|新しい作業を始める|このワークスペースに独立したターミナルを作成します。|名前|実行|閉じる|キャンセル|セッションを作成|作成中…|関係|2つのセッションをつなぐ|関連付け先|会話履歴を共有したり、セッションを変更したりせずに関係を追加します。|接続を追加|ターミナルは利用可能|ターミナルは利用不可|利用可否は不明|実行環境は不明|未インストール|追加日: {date}|作成元|関連付け|セッション|セッション操作|接続を追加するには、別のセッションを作成してください。|OMG cmux アプリでこのキャンバスを開いてください。|ネイティブアプリから無効なデータが返されました。接続を再試行してください。|セッションを作成しました|位置を保存できませんでした。|対話型の Python プロンプトを開きます。|プロンプトを送信せずに CLI を開きます。|ワークスペースが変更されました。このキャンバスを開き直してください。'
  };
  const catalogs = Object.fromEntries(Object.entries(rows).map(([locale, row]) => {
    const values = row.split('|');
    if (values.length !== keys.length) throw new Error(`Invalid OMG message catalog: ${locale}`);
    return [locale, Object.fromEntries(keys.map((key, i) => [key, values[i]]))];
  }));
  function localeFor(value) {
    const language = String(value || 'en').replaceAll('_', '-');
    if (/^zh-(TW|HK|MO|Hant)/i.test(language)) return 'zh-Hant';
    if (/^zh/i.test(language)) return 'zh-Hans';
    return catalogs[language] ? language : catalogs[language.split('-')[0]] ? language.split('-')[0] : 'en';
  }
  function translate(locale, key, values = {}) {
    const message = catalogs[localeFor(locale)][key] || catalogs.en[key] || key;
    return message.replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? `{${name}}`));
  }
  const api = {catalogs, keys, localeFor, translate};
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.OMGCanvasMessages = api;
})(typeof globalThis === 'object' ? globalThis : this);
